Select * from customer limit 20;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where lower (discount_applied )= 'yes' AND purchase_amount >= (SELECT AVG (purchase_amount)from customer);
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg (review_rating) desc
limit 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;
--  Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 
select subscription_status,
count(customer_id) as Total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as Total_revenue
from customer
group by subscription_status
order by Total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when LOWER(TRIM(discount_applied)) = 'yes' then 1 else 0 end)/COUNT(*),2)as Discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment.
With customer_type as (
select customer_id, previous_purchases,
case
 when previous_purchases = 1 then 'New'
 when previous_purchases between 2 AND 10 then'Returning'
 ELSE 'LoyaL'
 end as "Customer Segment"
 from customer
)
select "Customer Segment", count(*) as "Number of Customers"
from customer_type
Group by "Customer Segment"

--Q8. What are the top 3 most purchased products within each category?
WITH items_counts AS (
SELECT category,item_purchased,
count (customer_id) as Total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY count (customer_id)DESC)as item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT
  category,
  item_rank,
  item_purchased,
  Total_orders
FROM items_counts
WHERE item_rank<= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count (customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--Q10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
